version: "3.7"
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - web
      - internal
    depends_on:
      - api-ordermgmt
    restart: unless-stopped
  api-ordermgmt:
    image: "repasscloud/ordermgmt"
    restart: unless-stopped
    networks:
      - internal
    