version: "3.7"
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - web
      - internal
    depends_on:
      - api01
      - api02
    restart: unless-stopped
  api01:
    image: repasscloud/api.engine:rev5
    restart: unless-stopped
    networks:
      - internal
  api02:
    image: repasscloud/api.engine:rev5
    restart: unless-stopped
    networks:
      - internal
    