version: "3.7"
networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge
services:
  caddy:
    image: "caddy:2.4.6-alpine"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    networks:
      - web
      - internal
    depends_on:
      - nginx
      - api01
      - api02
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080"
    networks:
      - internal
    depends_on:
      - api01
      - api02
    restart: unless-stopped
  api01:
    image: repasscloud/api.engine:rev5
    restart: unless-stopped
    networks:
      - internal
  api02:
    image: repasscloud/api.engine:rev5
    restart: unless-stopped
    networks:
      - internal